[package]
name = "dragonfly-agent"
version = "0.1.0"
edition = "2021"
authors = ["Sparx"]
description = "Agent for Dragonfly bare metal infrastructure management"

[dependencies]
dragonfly-common = { path = "../dragonfly-common" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }

# OS information gathering
sysinfo = "0.30" 