apiVersion: tinkerbell.org/v1alpha1
kind: Workflow
metadata:
  name: os-install-bc-24-11-35-1e-f7
  namespace: tink
spec:
  hardwareMap:
    device_1: bc:24:11:35:1e:f7
  hardwareRef: machine-bc-24-11-35-1e-f7
  templateRef: ubuntu
