apiVersion: tinkerbell.org/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2025-03-28T16:03:59Z"
  generation: 1
  name: os-install-bc-24-11-35-1e-f7
  namespace: tink
  resourceVersion: "912174"
  uid: 0abf1b8d-4221-4937-87c0-c0bb9e649a97
spec:
  hardwareMap:
    device_1: bc:24:11:35:1e:f7
  hardwareRef: machine-bc-24-11-35-1e-f7
  templateRef: ubuntu
status:
  bootOptions:
    allowNetboot: {}
  conditions:
  - message: template rendered successfully
    reason: Complete
    status: "True"
    time: "2025-03-28T16:03:59Z"
    type: TemplateRenderedSuccess
  currentAction: kexec to boot OS
  globalTimeout: 9800
  state: STATE_FAILED
  tasks:
  - actions:
    - environment:
        COMPRESSED: "true"
        DEST_DISK: /dev/sda
        IMG_URL: http://10.7.1.30:8080/ubuntu/jammy-server-cloudimg-amd64.raw.gz
      image: quay.io/tinkerbell/actions/image2disk:latest
      name: stream image
      seconds: 162
      startedAt: "2025-03-28T16:04:00Z"
      status: STATE_SUCCESS
      timeout: 9600
    - environment:
        CONTENTS: |
          datasource:
            Ec2:
              metadata_urls: ["http://10.7.1.30:50061"]
              strict_id: false
          manage_etc_hosts: localhost
          warnings:
            dsid_missing_source: off
          users:
            - default
          disable_root: true
          ssh_import_id:
            - gh:zorlin
            - gh:michatinkers
          packages:
            - qemu-guest-agent
          runcmd:
            - systemctl enable qemu-guest-agent
            - systemctl start qemu-guest-agent
        DEST_DISK: /dev/sda1
        DEST_PATH: /etc/cloud/cloud.cfg.d/10_tinkerbell.cfg
        DIRMODE: "0700"
        FS_TYPE: ext4
        GID: "0"
        MODE: "0600"
        UID: "0"
      image: quay.io/tinkerbell/actions/writefile:latest
      name: write cloud-init config
      seconds: 6
      startedAt: "2025-03-28T16:06:42Z"
      status: STATE_SUCCESS
      timeout: 90
    - environment:
        CONTENTS: |
          datasource: Ec2
        DEST_DISK: /dev/sda1
        DEST_PATH: /etc/cloud/ds-identify.cfg
        DIRMODE: "0700"
        FS_TYPE: ext4
        GID: "0"
        MODE: "0600"
        UID: "0"
      image: quay.io/tinkerbell/actions/writefile:latest
      name: write ds-identify config
      seconds: 2
      startedAt: "2025-03-28T16:06:48Z"
      status: STATE_SUCCESS
      timeout: 90
    - environment:
        CONTENTS: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              id0:
                match:
                  name: en*
                dhcp4: true
        DEST_DISK: /dev/sda1
        DEST_PATH: /etc/netplan/config.yaml
        DIRMODE: "0755"
        FS_TYPE: ext4
        GID: "0"
        MODE: "0644"
        UID: "0"
      image: quay.io/tinkerbell/actions/writefile:latest
      name: write netplan config
      seconds: 5
      startedAt: "2025-03-28T16:06:50Z"
      status: STATE_SUCCESS
      timeout: 90
    - environment:
        BLOCK_DEVICE: /dev/sda3
        CMD_LINE: root=/dev/sda3 ro
        FS_TYPE: ext4
        INITRD_PATH: /boot/initrd
        KERNEL_PATH: /boot/vmlinuz
      image: quay.io/tinkerbell/actions/kexec:latest
      name: kexec to boot OS
      pid: host
      seconds: 4
      startedAt: "2025-03-28T16:06:55Z"
      status: STATE_FAILED
      timeout: 90
    environment:
      GLOBAL_VALUE: my global value
    name: os installation
    volumes:
    - /dev:/dev
    - /dev/console:/dev/console
    - /lib/firmware:/lib/firmware:ro
    worker: bc:24:11:35:1e:f7
  templateRending: successful
