---
apiVersion: tinkerbell.org/v1alpha1
kind: Template
metadata:
  name: autoregister
  namespace: tink
spec:
  data: |
    version: "0.1"
    name: autoregister
    global_timeout: 600
    tasks:
      - name: register
        worker: "{{.device_1}}"
        actions:
          - name: auto-register
            image: alpine:3.17
            timeout: 60
            command: ["/bin/sh", "-c"]
            args:
              - |
                SERIAL=$(cat /sys/class/dmi/id/product_uuid)
                curl -X POST http://10.7.1.30:8080/v1/hardware \
                  -H 'Content-Type: application/json' \
                  --data '{"id":"'"$SERIAL"'","instance":{"id":"'"$SERIAL"'","allow_pxe":false}}'
